//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KECJobs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup_Experiences
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lookup_Experiences()
        {
            this.tbl_JobOpenings = new HashSet<JobOpenings>();
        }
    
        public int ExperienceID { get; set; }
        public string ExperienceShort_Description { get; set; }
        public string Exprerience_Logn_Description { get; set; }
        public bool GraduateGroup { get; set; }
        public bool ExperienceGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobOpenings> tbl_JobOpenings { get; set; }
    }
}
