//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KECJobs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int RegistrationID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Gender { get; set; }
        public int QualificationID { get; set; }
        public int PositiontypeID { get; set; }
        public string AreaOfIntrest { get; set; }
        public string EmailAddress { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public string ResumeFilePath { get; set; }
    
        public virtual tbl_lookup_PositionType tbl_lookup_PositionType { get; set; }
        public virtual tbl_Lookup_Qualifications tbl_Lookup_Qualifications { get; set; }
        public virtual tbl_Lookup_MaritalStatus tbl_Lookup_MaritalStatus { get; set; }
    }
}
