//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KECJobs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillDevelopment
    {
        public int SkillDevID { get; set; }
        public string OrgName { get; set; }
        public string TrainingCources { get; set; }
        public Nullable<int> DurationId { get; set; }
        public Nullable<int> CostId { get; set; }
        public string Criteria { get; set; }
        public string Locations { get; set; }
        public string OtherInfo { get; set; }
        public string ContactDetails { get; set; }
    
        public virtual Lookup_Costs tbl_lookup_costs { get; set; }
        public virtual Lookup_Duration tbl_Lookup_Duration { get; set; }
    }
}
