//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KECJobs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Lookup_Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Lookup_Roles()
        {
            this.tbl_Users = new HashSet<tbl_Users>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public bool isAdmin { get; set; }
        public bool isJobsEditor { get; set; }
        public bool isRegistrationEditor { get; set; }
        public bool isReferenceEditor { get; set; }
        public bool IsGuest { get; set; }
        public bool Active { get; set; }
        public bool isSkillDevelopmentEditor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Users> tbl_Users { get; set; }
    }
}
